openapi: "3.0.0"
info:
  title: ECOM Wishlist
  version: 1.0.0
servers:
  - url: http://localhost:8080/wishlist
paths:
  /wishlist:
    get:
      summary: Lista todos produtos desejados por um cliente
      operationId: listWishes
      responses:
        '200':
          description: Uma lista de desejos
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Wishlist"
components:
  schemas:
    Wish:
      type: object
      properties:
        wishId:
          type: integer
          format: int64
        date:
          type: integer
          format: int32
        productId:
          type: integer
          format: int64
    Wishlist:
      type: object
      properties:
        wishes:
          type: array
          items:
            $ref: '#/components/schemas/Wish'
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

