# Adicionar um produto na Wishlist do cliente;
# Remover um produto da Wishlist do cliente;
# Consultar todos os produtos da Wishlist do cliente;
GET http://localhost:8080/wishlist
# Consultar se um determinado produto está na Wishlist do cliente;


