ecom:
  web:
    cors:
      mappings:
        - path: "/**"
          origins:
            - "*"
          methods:
            - "GET"
            - "POST"
            - "PUT"
            - "DELETE"
            - "OPTIONS"
          allowed-headers:
          exposed-headers:
          allow-credentials: false
          maxAge: 3600
